server:
  port: 8083

spring:
  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            trusted:
              packages: com.example.notificationservice.dto
            value:
              default:
                type: com.example.notificationservice.dto.NotificationRequest

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9090/eureka/
#    fetch-registry: true
#    register-with-eureka: true

