spring:
  application:
    name: users-service

  datasource:
    url: jdbc:mysql://localhost:3306/UserDb
    username: root
    password: Shubham@123k

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  config:
    import: optional:configserver:http://localhost:8888

  # Uncomment if you want to enable Eureka client
  #eureka:
  #  instance:
  #    prefer-ip-address: true
  #  client:
  #    fetch-registry: true
  #    register-with-eureka: true
  #    service-url:
  #      defaultZone: http://localhost:9090/eureka

logging:
  level:
    org.springframework.security: DEBUG
