server:
  port: 8082

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/UserDb
    username: root
    password: Shubham@123k

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  config:
    import: optional:configserver:http://localhost:8888

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false

logging:
  level:
    org.springframework.security: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      verifyProduct:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 5

  retry:
    instances:
      productRetry:
        maxAttempts: 3               # अधिकतम 3 बार ट्राय करेगा
        waitDuration: 2s            # हर ट्राय के बीच 2 सेकंड का इंतजार

  ratelimiter:
    instances:
      productRateLimiter:
        limitForPeriod: 10           # 10 सेकंड में अधिकतम 5 बार ऑर्डर
        limitRefreshPeriod: 20s
        timeoutDuration: 1000ms      # लिमिट ओवर हो तो 500ms तक इंतजार


management.endpoints.web.exposure.include: "*"


# Uncomment and edit these Eureka settings if needed
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:9090/eureka
